import AppKit
import Foundation

/// Polls the general pasteboard and records new text and image content.
///
/// macOS has no pasteboard-change notification, so like every clipboard
/// manager we poll `changeCount` on a short interval. The check is cheap:
/// it only reads content when the count actually changes.
final class ClipboardMonitor {
    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Content types that password managers and similar tools use to flag
    /// content that must not be recorded.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Images bigger than this are ignored to keep the history file small.
    private static let maxImageBytes = 25 * 1024 * 1024

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.check()
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after this app writes to the pasteboard itself, so the
    /// write is not recorded as a new (duplicate) history entry.
    func markOwnChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        guard let types = pasteboard.types, !types.isEmpty else { return }
        if types.contains(Self.concealedType) || types.contains(Self.transientType) || types.contains(Self.autoGeneratedType) {
            return
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(string)
            return
        }

        let hasImage = types.contains(.tiff) || types.contains(.png)
        if hasImage, let image = NSImage(pasteboard: pasteboard), let png = image.pngRepresentation() {
            guard png.data.count <= Self.maxImageBytes else { return }
            store.addImage(pngData: png.data, width: png.width, height: png.height)
        }
    }
}

extension NSImage {
    struct PNGRepresentation {
        let data: Data
        let width: Int
        let height: Int
    }

    func pngRepresentation() -> PNGRepresentation? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }
        return PNGRepresentation(data: png, width: rep.pixelsWide, height: rep.pixelsHigh)
    }
}
