import AppKit
import Foundation
import ImageIO

/// Polls the general pasteboard and records new files, text, and images.
///
/// macOS has no pasteboard-change notification, so like every clipboard
/// manager we poll `changeCount` on a short interval. The check is cheap:
/// it only reads content when the count actually changes.
final class ClipboardMonitor {
    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Content types that password managers and similar tools use to flag
    /// content that must not be recorded.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let jpegType = NSPasteboard.PasteboardType("public.jpeg")

    /// Images bigger than this are ignored to keep the history folder small.
    private static let maxImageBytes = 25 * 1024 * 1024

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.check()
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after this app writes to the pasteboard itself, so the
    /// write is not recorded as a new (duplicate) history entry.
    func markOwnChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        guard let types = pasteboard.types, !types.isEmpty else { return }
        if types.contains(Self.concealedType) || types.contains(Self.transientType) || types.contains(Self.autoGeneratedType) {
            return
        }

        // 1. Files copied in Finder (or any app that puts file URLs on the pasteboard).
        if AppSettings.shared.recordFiles, types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            store.addFiles(urls)
            return
        }

        // 2. Plain text.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(string)
            return
        }

        // 3. Image data.
        if var payload = Self.imagePayload(from: pasteboard, types: types) {
            guard payload.data.count <= Self.maxImageBytes else { return }
            if AppSettings.shared.compressLargeImages {
                payload = ImageCompressor.compressIfWorthwhile(payload)
            }
            store.addImage(data: payload.data, fileExtension: payload.fileExtension, width: payload.width, height: payload.height)
        }
    }

    struct ImagePayload {
        let data: Data
        let fileExtension: String
        let width: Int
        let height: Int
    }

    /// Prefers the original encoded bytes (JPEG, then PNG) so photos are not
    /// inflated by a lossless re-encode. Falls back to converting whatever
    /// image the pasteboard offers into PNG.
    static func imagePayload(from pasteboard: NSPasteboard, types: [NSPasteboard.PasteboardType]) -> ImagePayload? {
        if types.contains(jpegType), let data = pasteboard.data(forType: jpegType), let size = pixelSize(of: data) {
            return ImagePayload(data: data, fileExtension: "jpg", width: size.width, height: size.height)
        }
        if types.contains(.png), let data = pasteboard.data(forType: .png), let size = pixelSize(of: data) {
            return ImagePayload(data: data, fileExtension: "png", width: size.width, height: size.height)
        }
        guard NSImage.canInit(with: pasteboard), let image = NSImage(pasteboard: pasteboard), let png = image.pngRepresentation() else {
            return nil
        }
        return ImagePayload(data: png.data, fileExtension: "png", width: png.width, height: png.height)
    }

    private static func pixelSize(of data: Data) -> (width: Int, height: Int)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = props[kCGImagePropertyPixelWidth] as? Int,
              let height = props[kCGImagePropertyPixelHeight] as? Int else { return nil }
        return (width, height)
    }
}

extension NSImage {
    struct PNGRepresentation {
        let data: Data
        let width: Int
        let height: Int
    }

    func pngRepresentation() -> PNGRepresentation? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }
        return PNGRepresentation(data: png, width: rep.pixelsWide, height: rep.pixelsHigh)
    }
}
